pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
      checkLatest: true
    displayName: "Install Node.js"

  - script: |
      npm ci
      npm test
    displayName: "npm install and test"

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: junit.xml

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: coverage/cobertura-coverage.xml
