version: 1
update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: live
    default_reviewers:
      - jbhannah
    automerged_updates:
      - match:
          update_type: all
    version_requirement_updates: auto
