---
resources:
  - name: src
    type: git
    icon: github-circle
    source:
      uri: https://github.com/jbhannah/jbhannah.net.git
      branch: master
  - name: deps
    type: git
    icon: github-circle
    source:
      uri: https://github.com/jbhannah/jbhannah.net.git
      branch: master
      paths:
        - Dockerfile
        - package.json
        - package-lock.json
  - name: buildkit
    type: registry-image
    source:
      repository: moby/buildkit
      tag: master
  - name: base
    type: registry-image
    source:
      repository: jbhannah/jbhannah.net
      tag: base
      username: ((docker.username))
      password: ((docker.password))
  - name: dist
    type: registry-image
    source:
      repository: jbhannah/jbhannah.net
      username: ((docker.username))
      password: ((docker.password))

jobs:
  - name: base
    plan:
      - get: deps
        trigger: true
      - task: build
        privileged: true
        config:
          platform: linux
          image: buildkit
          inputs:
            - name: deps
          outputs:
            - name: image
          run:
            path: buildctl-daemonless.sh
            args:
              - build
              - --frontend=dockerfile.v0
              - --local=context=./deps
              - --local=dockerfile=./deps
              - --opt=target=base
              - --import-cache=type=registry,ref=docker.io/jbhannah/jbhannah.net:base
              - --export-cache=type=inline
              - --output=type=docker,name=jbhannah/jbhannah.net:base,dest=./image/image.tar
      - put: base
        params:
          image: image/image.tar
  - name: lint
    plan:
      - in_parallel:
          - get: src
            trigger: true
          - get: base
            trigger: true
            passed:
              - base
      - task: lint
        image: base
        config:
          platform: linux
          inputs:
            - name: src
          run:
            dir: src
            path: npm
            args:
              - run
              - lint
  - name: test
    plan:
      - in_parallel:
          - get: src
            trigger: true
          - get: base
            trigger: true
            passed:
              - base
      - task: test
        image: base
        config:
          platform: linux
          inputs:
            - name: src
          run:
            dir: src
            path: npm
            args:
              - test
  - name: build
    plan:
      - get: src
        trigger: true
        passed:
          - lint
          - test
      - task: build
        image: buildkit
        inputs:
          - name: base
          - name: src
        outputs:
          - name: image
        run:
          path: buildctl-daemonless.sh
          args:
            - build
            - --frontend=dockerfile.v0
            - --local=context=./src
            - --local=dockerfile=./src
            - --import-cache=type=registry,ref=docker.io/jbhannah/jbhannah.net:base
            - --output=type=docker,name=jbhannah/jbhannah.net,dest=./image/image.tar
      - put: dist
        params:
          image: image/image.tar
