---
resources:
  - name: src
    type: git
    icon: github-circle
    source:
      uri: https://github.com/jbhannah/jbhannah.net.git
      branch: master
      ignore_paths: &paths
        - ci/pipeline.yml
        - Dockerfile
        - package.json
        - package-lock.json
  - name: deps
    type: git
    icon: github-circle
    source:
      uri: https://github.com/jbhannah/jbhannah.net.git
      branch: master
      paths: *paths
  - name: buildkit
    type: registry-image
    source:
      repository: jbhannah/buildkit
      tag: master
  - name: base
    type: registry-image
    source:
      repository: jbhannah/jbhannah.net
      tag: base
      username: jbhannah
      password: ((docker.password))
  - name: build
    type: registry-image
    source:
      repository: jbhannah/jbhannah.net
      tag: build
      username: jbhannah
      password: ((docker.password))
  - name: dist
    type: registry-image
    source:
      repository: jbhannah/jbhannah.net
      username: jbhannah
      password: ((docker.password))

jobs:
  - name: base
    plan:
      - in_parallel:
          - get: deps
            trigger: true
          - get: buildkit
      - task: build
        image: buildkit
        privileged: true
        config:
          platform: linux
          inputs:
            - name: deps
          outputs:
            - name: image
          run:
            path: buildctl-daemonless.sh
            args:
              - build
              - --frontend=dockerfile.v0
              - --local=context=./deps
              - --local=dockerfile=./deps
              - --opt=target=base
              - --import-cache=type=registry,ref=docker.io/jbhannah/jbhannah.net:base
              - --export-cache=type=inline
              - --output=type=docker,name=jbhannah/jbhannah.net:base,dest=./image/image.tar
      - put: base
        params:
          image: image/image.tar
  - name: build
    plan:
      - in_parallel:
          - get: src
            trigger: true
          - get: base
            trigger: true
            passed:
              - base
      - task: build
        image: buildkit
        privileged: true
        config:
          platform: linux
          inputs:
            - name: src
          outputs:
            - name: image
          run:
            path: buildctl-daemonless.sh
            args:
              - build
              - --frontend=dockerfile.v0
              - --local=context=./src
              - --local=dockerfile=./src
              - --opt=target=build
              - --import-cache=type=registry,ref=docker.io/jbhannah/jbhannah.net:base
              - --import-cache=type=registry,ref=docker.io/jbhannah/jbhannah.net:build
              - --export-cache=type=inline
              - --output=type=docker,name=jbhannah/jbhannah.net:build,dest=./image/image.tar
      - put: build
        params:
          image: image/image.tar
  - name: lint
    plan:
      - get: build
        trigger: true
        passed:
          - build
      - task: lint
        image: build
        config:
          platform: linux
          inputs:
            - name: src
          run:
            path: sh
            args:
              - -c
              - |
                cd /app
                npm run lint
  - name: test
    plan:
      - get: build
        trigger: true
        passed:
          - build
      - task: test
        image: build
        config:
          platform: linux
          inputs:
            - name: src
          run:
            path: sh
            args:
              - -c
              - |
                cd /app
                npm test
  - name: dist
    plan:
      - in_parallel:
          - get: buildkit
          - get: src
            trigger: true
            passed:
              - lint
              - test
      - task: build
        image: buildkit
        config:
          platform: linux
          inputs:
            - name: src
          outputs:
            - name: image
          run:
            path: buildctl-daemonless.sh
            args:
              - build
              - --frontend=dockerfile.v0
              - --local=context=./src
              - --local=dockerfile=./src
              - --import-cache=type=registry,ref=docker.io/jbhannah/jbhannah.net:build
              - --output=type=docker,name=jbhannah/jbhannah.net,dest=./image/image.tar
      - put: dist
        params:
          image: image/image.tar
